name: apex
favicon: null
layout_spectrum: 0.24625
typography_spectrum: 0.49112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f1b542'
    - '#252838'
    - '#c8c9cd'
    - '#92939b'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
