name: apex
favicon: null
layout_spectrum: 0.47588
typography_spectrum: 0.45877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f4'
    - '#f0b642'
    - '#252838'
    - '#434554'
    - '#6b6b6d'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
