typography_spectrum: 0.18649165937677026
color:
  brandColors:
    - '#f2f2f4'
    - '#f0b642'
    - '#252838'
    - '#434554'
    - '#6b6b6d'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41980754770338535
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff3a263d-8a2b-426f-91aa-6cec3dc32832.png
name: apex
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/26a2478f-5979-4a99-a15e-db114ad02500.png
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
purpose: []
